#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"
source ../local_install.bash
to_link=(".gitconfig" ".gitignore_global")
install "${to_link[@]}"
