#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"
source ../local_install.bash
to_link=(".bash_aliases"  ".bash_completion"  ".bash_logout"  ".bashrc"  ".dircolors"  ".profile")
install "${to_link[@]}"
